name: Build AUR in Docker and Archive Upload

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-aur:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (optional)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t aur-builder:latest .

      - name: Run AUR builder container
        run: |
          # 将仓库内的 upload/ 和 packages/ 作为卷挂载到容器
          # 其中 /opt/upload 会被容器中的脚本 chmod 777
          docker run --rm \
            -v "${{ github.workspace }}/upload:/opt/upload" \
            -v "${{ github.workspace }}/packages:/opt/packages" \
            aur-builder:latest

      - name: Install archiver (7z)
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Compress upload/ (single archive first)
        working-directory: ${{ github.workspace }}
        run: |
          if [ ! -d "upload" ]; then
            echo "ERROR: upload/ not found"
            exit 1
          fi

          # 先生成单一 7z 包
          7z a -mx=9 -mmt=on "upload.7z" ./upload/*

          BYTES=$(stat -c%s "upload.7z")
          echo "Packed size (bytes): ${BYTES}"

          # 阈值 1.9GB
          THRESHOLD=$((1900 * 1024 * 1024))

          if [ "${BYTES}" -gt "${THRESHOLD}" ]; then
            echo "is_split=true" >> $GITHUB_ENV
            # 删除单包，改用原生 7z 多卷重新打包（每卷 1900MB）
            rm -f upload.7z
            7z a -mx=9 -mmt=on -v1900m "upload.7z" ./upload/*
            # 结果会是 upload.7z.001, upload.7z.002, ...
          else
            echo "is_split=false" >> $GITHUB_ENV
          fi

      - name: Prepare release tag (Asia/Singapore -> mmddyyyy-hh-mm-ss)
        id: prep_tag
        run: |
          TZ=Asia/Singapore
          VERSION=$(TZ=$TZ date '+%m%d%Y-%H-%M-%S')
          echo "RELEASE_TAG=$VERSION" >> $GITHUB_ENV
          echo "Release tag: $VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
      
      - name: Upload multi-volume archives to Release (only if >1.9GB)
        if: env.is_split == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            upload.7z.*
